workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' 
      when: always

    - when: never

stages:
  - BUILD & REPORTS


BUILD-REPORT:
  image: node:20
  stage: BUILD & REPORTS
  before_script: 
    - echo "antes de los scripts"
  script:
    - bash ./api_vault.sh
    - bash ./install_depend.sh
  after_script:
    - mv output/* public
  artifacts:
    when: always 
    paths:
      - public
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

