workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' 
      when: always

    - when: never

stages:
  - BUILD & REPORTS


BUILD-REPORT:
  image: node:20
  stage: BUILD & REPORTS
  script:
    - npm ci
    - npx playwright install-deps 
    - npx playwright install
    - npm run cc || true
    - mv output/* public
  artifacts:
    when: always 
    paths:
      - public
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

