name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v3

    - name: Download secrets
      run: |
        doppler secrets download \
          -p ${{ secrets.DOPPLER_PROJECT }} \
          -c "${{ github.ref_name }}_${{ github.event.repository.name }}" \
          --no-file --format env \
          -t "${{ secrets.DOPPLER_TOKEN }}" > .env

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps > /dev/null

    - name: Run Playwright tests
      run: npm run cc
      env:
        CI: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          output/
          reports/
        retention-days: 1